### ISSUE TITLE
10 - mettre à jour un sixième jeu sur la page

### ISSUE THREAD

**Issue by yanngv29** [yanngv29/ensim-git-tp2#10]
mettre a jour un jeu sur la page pour qu'il corresponde à un jeu de votre choix.
Il faut changer l'image, le texte , les étiquettes, etc ...

**Comment by aloevera99** [comment]
Je m'en occupe :)

**Comment by yanngv29** [comment]
petit soucis sur l'affichage de la fiche du monopoly.
