### ISSUE TITLE
2 - Changer la section "About Academy Dices Games"

### ISSUE THREAD

**Issue by yanngv29** [yanngv29/ensim-git-tp2#2]
Dans la page , modifier la partie "About Academy Dices Games" en modifiant l'image et le texte pour que cela reflete le nouveau nom de la page "Les As de l'ENSIM"

**Comment by SurprisedBark12** [comment]
Je m'en charge - Dhruv MAULLOO

**Comment by yanngv29** [comment]
Merci de résoudre le conflit
